### ISSUE TITLE
Decide on the repo structure

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spDataLarge#1]

**Comment by Nowosad** [comment]
I've check the structure of the **rnaturaleartchhires** (https://github.com/ropenscilabs/rnaturalearthhires). It is basically a normal package. When somebody wants to use larger data files from the **rnaturalearth** package, the package checks if **rnaturaleartchhires** is installed. If not - it is installing "hires" package though not from CRAN (https://github.com/ropenscilabs/rnaturalearth/blob/master/R/install-rnaturalearthhires.r). 

Alternatively is something like here - https://github.com/jsta/externalrdata. I could add some new functions to the **spData** package, for example *sp_download()*:

```
#this would download srtm.tif into data/ folder
sp_download("srtm.tif", "data/") 
```

What do you think @Robinlovelace ? Are we going with the first or the second one?

**Comment by Robinlovelace** [comment]
I think either would work but suspect that the `externalrdata` approach would be simpler and easier to maintain. But worth double checking with pros in this area. Bob Rudis and Andy South and other Ropenci people may give good guidance.

On that note, would you like this to be reviewed by Ropensci? Good way to ensure it's polished when submitted to CRAN.

**Comment by Robinlovelace** [comment]
The rnaturalearth approach has the advantage of being tried and tested and already on CRAN though. So I'd be very happy with either.

**Comment by Nowosad** [comment]
Ok, I'll try to follow the **externalrdata** approach. 

I'm fine with the review of Ropensci. How we should start that?

**Comment by Robinlovelace** [comment]
Just create an issue here: https://github.com/ropensci/onboarding/issues/

**Comment by Nowosad** [comment]
Nice. I'll try to do that in the next days.

**Comment by Robinlovelace** [comment]
No rush. Equally I'm happy if we just go 'route 1' to submit it asap it you'd like to avoid bureaucratic overheads. But feedback could be really valuable so if you're up for that, sounds great! Closing the issue now in any case as it seem's we've decided a structure!
