### ISSUE TITLE
Please update drat repo to v0.5.0

### ISSUE THREAD

**Issue by jannes-m** [Nowosad/spDataLarge#22]

**Comment by Nowosad** [comment]
Thanks for letting me know, Jannes. The drat updates had been automatic in the past, but something seems to be broken now... I will investigate that.

**Comment by Nowosad** [comment]
@jannes-m please try now.

**Comment by jannes-m** [comment]
Perfect, now v0.5.0 is installed! Thanks a lot, @Nowosad!
