### ISSUE TITLE
Consider lazydata = FALSE and removing raster from imports

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spDataLarge#25]

**Comment by Nowosad** [comment]
@Robinlovelace @jannes-m What do you think about the idea of disabling lazydata and removing raster from imports in spDataLarge?

**Comment by Robinlovelace** [comment]
Good plan, :+1: needed by end of 2023, right?

**Comment by Nowosad** [comment]
At latest. I think we can do that when (a) we avoid using this feature (lazydata from spDataLarge) in geocompr2, and (b) geocompr2 is published.

**Comment by jannes-m** [comment]
Should I convert the raster files in the `landslides`, the `mongon` and the `ep_eco` dataset from **raster** to **terra**? Hopefully, the corresponding code adjustments will be not too labour intensive...

**Comment by Nowosad** [comment]
@jannes-m Correct me if I am wrong, but you cannot save terra objects directly to rda (you would need to use wrap to save it, and rast to read it). My current approach is to use `.tif` files saved in `inst/raster` and documented in the R folder (https://github.com/Nowosad/spDataLarge/blob/master/R/rasters.R).

**Comment by jannes-m** [comment]
Ah ok, no, I didn't know that one can not save terra objects as rds files. I didn't know either that you have already put most of the raster files into a raster folder. So thanks for letting me know. Some terrain attributes of the raster bricks `ta` and `ep` are still missing in the raster folder (catchment area, catchment slope, etc.) . Should we add them to the raster folder as multi-layer files or do you prefer to keep `ta` and `ep`?

**Comment by Nowosad** [comment]
I think we should use terra objects (or raster files) consistently through the book (and avoid raster objects). If you plan to use `ta` and `ep` in the book, then yes -- save them in the raster folder and add/update the documentation. Let me know if you need any help. J

**Comment by jannes-m** [comment]
Ok, then I will update these files and use **terra** files throughout the book.

**Comment by Nowosad** [comment]
This is not a priority now, but I made a version of the package that does not depend on {raster} -- https://github.com/Nowosad/spDataLarge/compare/noraster?expand=1. We can marge this PR whenever we want...

**Comment by Nowosad** [comment]
Merge completed.

**Comment by Robinlovelace** [comment]
Great work Jakub!
