### ISSUE TITLE
Old CRSs in Bristol objects

### ISSUE THREAD

**Issue by Robinlovelace** [Nowosad/spDataLarge#32]
Split out from https://github.com/Robinlovelace/geocompr/issues/835

One question: the script that generates the datasets are in geocompr, I guess that script should stay there?

**Comment by Nowosad** [comment]
Yep -- it should stay there.

**Comment by Robinlovelace** [comment]
Before and after of ways object. 

Before:

![image](https://user-images.githubusercontent.com/1825120/187182756-045b5e83-619f-4e48-8caa-e3455dba5b1e.png)

After (note new ways):

![image](https://user-images.githubusercontent.com/1825120/187182838-1377450f-7b54-4e16-a6b5-cb23205a3864.png)
